name: dynamic_height_list_view
description: "A Flutter package enabling dynamic height ListView and GridView layouts, perfect for responsive and adaptive interfaces with content of varying sizes."
version: 0.0.2
homepage: https://github.com/YudizAndroidSunny/dynamic_height_list_view
repository: https://github.com/YudizAndroidSunny/dynamic_height_list_view
issue_tracker: https://github.com/YudizAndroidSunny/dynamic_height_list_view/issues

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

topics:
  - dynamic-height-listview
  - dynamic-height-gridview
  - without-height-grid-view
  - without-height-list-view
  - responsive-ui

screenshots:
  - description: Flutter package for dynamic height ListView and GridView with varying content sizes.
    path: assets/gif/dynamic_height_list_view.gif

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
